### PR TITLE
Adds support for MSVC ARM64 target.

### PR DESCRIPTION
**Pull request by gongminmin**
Takes predefined macro _M_ARM64 in VS2015+ to detect ARM64 target.

### CODE REVIEW

**Comment by mclow** [comment]
This looks fine to me.  Please watch the bots, and ping me in a week if no problems have surfaced (so I'll remember to merge to master)

**Comment by gongminmin** [comment]
Sure. Thanks!

**Comment by gongminmin** [comment]
Seems no one's screaming in a week.

**Comment by mclow** [comment]
Merged.

**Pull request merged**
