### PR TITLE
to_int also should be called with this->

### PR DESCRIPTION
**Pull request by dpantele**
When I tried to build new policies base on existing, I've got problems with gcc which are fixed by adding this->

This change it not tested, but I can't see how it can break something.

### CODE REVIEW

**Comment by v4hn** [comment]
Is there a reason why this hasn't already been merged?
I just hit this bug as well and it's pretty annoying.

**Comment by mclow** [comment]
Well, I haven't merged it because this is the first I've seen it. However, if this was brand new, I would say "We don't merge into master - we merge into develop, let the tests cycle, and then merge from develop into master.".

However, I'll be happy to manually apply this today.

**Comment by mclow** [comment]
Or rather "we pull into develop", and then merge into master.

**Comment by v4hn** [comment]
On Fri, Jan 09, 2015 at 10:01:02AM -0800, Marshall Clow wrote:
> We don't merge into master - we merge into develop, let the tests cycle, and then merge from develop into master.

I wouldn't expect anything else from a boost module :-)

> However, I'll be happy to manually apply this today.

Thanks a lot!

**Comment by mclow** [comment]
Applied to develop. I'd appreciate it if you would watch the tests and let me know if you see any problems. Barring problems, I'll merge this to master early next week.

**Comment by v4hn** [comment]
As far as I can see there are no failing test cases due to this change.

**Pull request closed without merging**
